{
 "title": "Temperature-humidity",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "sensor_type", "label": "Sensor Type", "query": "temperature, humidity" },
   { "name": "start_time", "label": "Start Time", "query": "2023-08-12T00:00:00Z" },
   { "name": "end_time", "label": "End time", "query": "2023-08-12T23:59:59Z" }
  ]
 },
 "panels": [
  {
   "title": "Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"IoT_bucket\")\r\n  |> range(start: time(v: ${start_time}), stop: time(v: ${end_time}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${sensor_type}\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Testing\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Heat Index",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"heat_index\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Testing\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature heatmap",
   "type": "heatmap",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"IoT_bucket\")\r\n  |> range(start: time(v: ${start_time}), stop: time(v: ${end_time}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Testing\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity heatmap",
   "type": "heatmap",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"IoT_bucket\")\r\n  |> range(start: time(v: ${start_time}), stop: time(v: ${end_time}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Testing\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Current temperature", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 } },
  { "title": "Current Humidity", "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 } },
  {
   "title": "Maximum temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT_bucket\")\r\n  |> range(start: time(v: ${start_time}), stop: time(v: ${end_time}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Testing\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Minimum temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT_bucket\")\r\n  |> range(start: time(v: ${start_time}), stop: time(v: ${end_time}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Testing\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Maximum Humidity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT_bucket\")\r\n  |> range(start: time(v: ${start_time}), stop: time(v: ${end_time}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Testing\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Minimum Humidity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT_bucket\")\r\n  |> range(start: time(v: ${start_time}), stop: time(v: ${end_time}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"Testing\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}